# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genename', models.CharField(max_length=50)),
                ('cov_1x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('cov_10x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('cov_30x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('depth_ratio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('depth', models.DecimalField(decimal_places=0, max_digits=12)),
                ('match', models.DecimalField(decimal_places=0, max_digits=12)),
                ('match_ratio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
