# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreDB', '0002_dbmodel_cds'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genename', models.CharField(max_length=50)),
                ('RNAseqcov', models.BinaryField()),
                ('stringtie_complete', models.BinaryField()),
                ('stringtie_partial', models.BinaryField()),
                ('stringtie_isoform', models.BinaryField()),
                ('ORFannot_complete', models.BinaryField()),
                ('ORFannot_partial', models.BinaryField()),
                ('ORFannot_isoform', models.BinaryField()),
                ('transcriptname', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
                ('length', models.DecimalField(decimal_places=0, max_digits=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
